SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID =50; -- REALIZAR UNA CONSULTA CON LA CONDICION DONDE
/*
=
>
<
>=
<=
<> DISTINTO */
SELECT FIRST_NAME,SALARY  FROM EMPLOYEES WHERE SALARY>10000;
SELECT FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID <>50;