/* Condiciones 
AND C1 AND C2 >TRUE
OR C1 OR C2> TRUE
NOT >TRUE    
*/
SELECT * FROM EMPLOYEES WHERE SALARY > 5000 AND DEPARTMENT_ID=50; 
SELECT * FROM EMPLOYEES WHERE SALARY > 5000 OR DEPARTMENT_ID=50; 
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN (50,60); 