SELECT FIRST_NAME, HIRE_DATE, JOB_ID, SALARY FROM EMPLOYEES WHERE JOB_ID='IT_PROG' AND SALARY<6000;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (50,80) AND FIRST_NAME LIKE 'S%' AND SALARY > 3000;
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'S%' AND SALARY > 3000 AND (DEPARTMENT_ID=50 OR DEPARTMENT_ID=80);
SELECT * FROM EMPLOYEES WHERE JOB_ID='IT_PROG' AND phone_number LIKE '%5%' AND HIRE_DATE BETWEEN '01-01-07' AND '31-12-07';