SELECT * FROM EMPLOYEES
ORDER BY SALARY ASC;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE FIRST_NAME='David' 
ORDER BY FIRST_NAME, LAST_NAME;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE FIRST_NAME='David' 
ORDER BY FIRST_NAME, SALARY DESC;


SELECT FIRST_NAME, SALARY*12 FROM EMPLOYEES
ORDER BY 2; --AQUI INDICO LA POSICION DE LA COLUMNA, ES DECIR EL 2 EXPRESA SALARY*12

SELECT FIRST_NAME, SALARY*12 AS TOTAL FROM EMPLOYEES
ORDER BY TOTAL DESC;