SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC FETCH FIRST 5 ROWS ONLY; --ORDENA POR SALARIO DESCENDENTE (LOS MAYORES) TOMA SOLO LAS 5 FILAS
SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC FETCH FIRST 7 ROWS WITH TIES ; --ORDENA POR SALARIO DESCENDENTE (LOS MAYORES) TOMA LAS 7 FILAS Y LAS QUE TAMBIEN CUMPLAN CON EL RANGO

SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC OFFSET 5 ROWS FETCH FIRST 7 ROWS WITH TIES ; /* 
ORDENA POR SALARIO DESCENDENTE (LOS MAYORES) SALTA LAS 5 FILAS Y TOMA LAS 7 FILAS MÁS LAS QUE TAMBIEN CUMPLAN CON EL RANGO
*/

SELECT * FROM EMPLOYEES FETCH FIRST 20 PERCENT ROWS ONLY; --TOMA EL 20 PORCIENTO DE LA CONSULTA