SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID =50;
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME='John';
SELECT *FROM EMPLOYEES; -- UN NUMERO JULIANO ES UNO QUE SE ALMACENA Y REPRESENTA UNA FECHA GUARDA Y CALCULA EL DIA ESPECIAL
--1 DE ENERO 4712 AC
SELECT * FROM EMPLOYEES WHERE HIRE_DATE='21-06-07';