SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 6000;
SELECT *fROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-01-07' AND '01-01-09'; 
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME BETWEEN 'Douglas' AND 'Steven'; -- hace consulta entre los caracteres