SELECT *FROM EMPLOYEES WHERE department_id=100;
SELECT CITY, STREET_ADDRESS,country_id FROM LOCATIONS WHERE COUNTRY_ID='US';
SELECT COUNTRY_ID, region_id FROM COUNTRIES WHERE region_id = 3; 
SELECT FIRST_NAME, SALARY, MANAGER_ID FROM EMPLOYEES WHERE manager_id<> 114;
SELECT FIRST_NAME, hire_date FROM EMPLOYEES WHERE HIRE_DATE > '01-01-06';
SELECT FIRST_NAME, JOB_ID FROM employees WHERE job_id='ST_CLERK';
SELECT * FROM EMPLOYEES WHERE LAST_NAME='Smith';