SELECT FIRST_NAME, department_id FROM EMPLOYEES WHERE department_id BETWEEN 40 AND 60;
SELECT * FROM EMPLOYEES WHERE hire_date BETWEEN '01-01-02' AND '01-01-04';
SELECT * FROM EMPLOYEES WHERE LAST_NAME BETWEEN 'D' AND 'G';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN(30,60,90);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN('IT_PROG', 'PU_CLERK');
SELECT * FROM LOCATIONS WHERE COUNTRY_ID IN ('JP', 'UK');