/*Una subconsulta es una query o select que devuelve
que puede ser utilizado por otra consulta*/
SELECT MAX(SALARY) FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY=24000;
--ESTAS SON DOS QUERIES DISTINTAS HAY QUE USAR LA MISMA
--ESTA ES UNA SUBCONSULTA
SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES);

--WHERE
--HAVING
--FROM
--Si corremos este devuelve un error ya que la subconsulta solo puede devolver
--una fila
SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES);