--SABER DEPARTAMENTOS CUYOS EMPLEADOS GANAN MÁS QUE LA MEDIA
SELECT DEPARTMENT_ID,ROUND(AVG(SALARY)) AS "MEDIA DEPARTAMENTO" FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > (SELECT AVG(SALARY) FROM EMPLOYEES);

--NO SE PUEDE USAR WHERE PORQUE ES GROUP BY