--USO DEL ANY
/*DEVUELVE LA CONDICIÓN QUE ESTE EN ESAS OPCIONES
TIENE QUE IR CON OTRO OPERADOR > O < */
---> ANY < ANY
--BUSCAR SALARIOS QUE GANEN MÁS QUE LOS PROGRAMADORES, SIN QUE APAREZCAN LOS PROGRAMADORES
SELECT FIRST_NAME, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEES
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE JOB_ID='IT_PROG')
AND JOB_ID <>'IT_PROG';

--ALL TIENE QUE COINCIDIR TODOS
SELECT FIRST_NAME, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEES
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE JOB_ID='IT_PROG')
AND JOB_ID <>'IT_PROG';