--SUBCONSULTAS SINCRONIZADAS
--LA SUBCONSULTA
SELECT DEPARTMENT_ID, FIRST_NAME, SALARY 
FROM EMPLOYEES
WHERE (DEPARTMENT_ID, SALARY) IN (SELECT DEPARTMENT_ID,MAX(SALARY)
FROM EMPLOYEES GROUP BY DEPARTMENT_ID);

SELECT DEPARTMENT_ID,MAX(SALARY)
FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

--la siguiente operación no es soportado en otras bases de datos
--primer paso crear un alias
SELECT DEPARTMENT_ID, FIRST_NAME,SALARY
FROM EMPLOYEES EMP 
WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=EMP.DEPARTMENT_ID);
--DA EL MISMO RESULTADO
/*TENEMOS UNA TABLA PRINCIPAL Y UNA SECUNDARIA, EN ESTE CASO EMPLOYEES Y EMPLOYEES, LA TABLA
PRINCIPAL SE LLAMARÁ EMP Y SE USARÁ EN LA SUBCONSULTA

PRIMER EMPLEADO
--10 TOMAS 100

POR CADA FILA DE LA QUERY PRINCIPAL SE LE PASA UNO O VARIOS VALORES A LA SUBCONSULTA, ES POTENTE PERO TIENE
UN EFECTO SECUNDARIO DESAGRADABLE, SE EJECUTA TANTAS VECES COMO EXISTAN FILAS EN LA PRINCIPAL, RECALCULA
LA SUBCONSULTA
*/