--EXISTS NO EXISTS
-- HACE PREGUNTAS SIEMPRE Y CUANDO LA SUBCONSULTA NO DEVUELVA UNA FILA
--SABER QUE DEPARTAMENTOS NO TIENEN EMPLEADOS
SELECT DEPARTMENT_NAME FROM DEPARTMENTS DEPT
WHERE NOT EXISTS(SELECT * FROM EMPLOYEES
                 WHERE DEPARTMENT_ID=DEPT.DEPARTMENT_ID);
/*El not exists hace un true o un false, muestra los departamentos
donde no haya empleados*/
SELECT DEPARTMENT_NAME FROM DEPARTMENTS DEPT
WHERE EXISTS(SELECT * FROM EMPLOYEES
                 WHERE DEPARTMENT_ID=DEPT.DEPARTMENT_ID);