-- SELECCIONAR EL NOMBRE, SALARIO Y DEPARTAMENTO DE LOS EMPLEADOS QUE GANEN
--MÁS  QUE CUALQUIERA DE LOS SALARIOS MÁXIMOS DE LOS DEPARTAMENTOS 50,60 Y 70
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY > ANY (SELECT MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID
HAVING DEPARTMENT_ID IN ('50','60','70'));

--INDICAR EL NOMBRE DE LOS DEPARTAMENTOS CUYO SALARIO MEDIO SEA SUPERIOR A 9000
--USAR EL OPERADOR IN
SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID IN 
(SELECT DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING
AVG(SALARY)>9000);

/*INDICAR EL NOMBRE DEL EMPLEADO, EL NOMBRE DEL DEPARTAMENTO, EL SALARIO
 DE LOS EMPLEADOS QUE TENGAN EL SALARIO MÁXIMO DE SU DEPARTAMENTO.
 ORDENADO POR SALARIO DESCENDENTEMENTE. USAR EL OPERADOR IN*/
 SELECT FIRST_NAME, DEPARTMENT_NAME,SALARY
 FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID)
 WHERE (DEPARTMENT_ID,SALARY)IN 
 (SELECT DEPARTMENT_ID,MAX(SALARY) 
                       FROM EMPLOYEES 
                       GROUP BY DEPARTMENT_ID)
 ORDER BY SALARY DESC;
 
/*Realizar el mismo procedimiento pero con subconsulta sincronizada */
SELECT FIRST_NAME DEPARTMENT_NAME,SALARY FROM EMPLOYEES EMP JOIN DEPARTMENTS DEPT
ON(EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID)
WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES
                     WHERE DEPARTMENT_ID=EMP.DEPARTMENT_ID
                     GROUP BY DEPARTMENT_ID)
ORDER BY SALARY DESC;

/*Indicar los datos de los empleados que ganen más que todos los empleados del
departamento 100. Usar el operador ALL*/
SELECT * FROM EMPLOYEES 
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID=100);

/*Mostrar los empleados que tienen el mayor salario de su departamento
usar subconsultas sincronizadas*/
SELECT FIRST_NAME, DEPARTMENT_NAME,SALARY FROM EMPLOYEES EMP JOIN DEPARTMENTS DEPT
ON(EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID)
WHERE SALARY =(SELECT MAX(SALARY) FROM EMPLOYEES 
                WHERE DEPARTMENT_ID=EMP.DEPARTMENT_ID
                GROUP BY DEPARTMENT_ID);
                
/*Visualizar las ciudades en las que haya algún departamento. Debemos usar consultas
sincronizadas y el operador EXISTS*/
SELECT CITY FROM LOCATIONS LOCT
WHERE EXISTS (SELECT * FROM DEPARTMENTS
             WHERE LOCATION_ID=LOCT.LOCATION_ID);
/*Visualizar las regiones donde no hay departamentos. Usar subconsultas
sincronizadas y el operador NOT EXISTS*/
SELECT REGION_NAME FROM REGIONS REGIONES
WHERE NOT EXISTS (SELECT * FROM COUNTRIES
                  NATURAL JOIN
                  LOCATIONS
                  NATURAL JOIN
                  DEPARTMENTS
                  WHERE REGION_ID=REGIONES.REGION_ID);
