--Ver operadores de conjunto o set operators in sql
CREATE TABLE REGIONS1
(
 REGION_ID NUMBER,
 REGION_NAME VARCHAR2(25)
);
INSERT INTO REGIONS1 VALUES(1,'Europe');
INSERT INTO REGIONS1 VALUES(3,'Asia');
INSERT INTO REGIONS1 VALUES(6,'Australia');
INSERT INTO REGIONS1 VALUES(8,'Antartica');

commit;
