/*los tipos de las columnas debe ser iguales, no los nombres los tipos*/
--USANDO UNIÓN LOS COMBINA PERO ELIMINA DUPLICADOS
SELECT REGION_ID,REGION_NAME FROM REGIONS 
UNION
SELECT REGION_ID,REGION_NAME FROM REGIONS1;

--USANDO UNIÓN ALL LOS COMBINA TAMBIEN DUPLICADOS
SELECT REGION_ID,REGION_NAME FROM REGIONS 
UNION ALL
SELECT REGION_ID,REGION_NAME FROM REGIONS1;

--USANDO INTERSECT COMBINA SOLO DUPLICADOS
SELECT REGION_ID,REGION_NAME FROM REGIONS 
INTERSECT
SELECT REGION_ID,REGION_NAME FROM REGIONS1;

--USANDO MINUS ELIMINA LOS DATOS DE UNA TABLA MENOS LA OTRA
SELECT REGION_ID,REGION_NAME FROM REGIONS 
MINUS
SELECT REGION_ID,REGION_NAME FROM REGIONS1;

SELECT REGION_ID,REGION_NAME FROM REGIONS1 
MINUS
SELECT REGION_ID,REGION_NAME FROM REGIONS;

