--PROBAR LOS 4 OPERADORES DE CONJUNTO
SELECT * FROM COCHES1
UNION
SELECT * FROM COCHES2;

SELECT * FROM COCHES1
UNION ALL
SELECT * FROM COCHES2;

SELECT * FROM COCHES1
INTERSECT
SELECT * FROM COCHES2;

SELECT * FROM COCHES1
MINUS
SELECT * FROM COCHES2;

SELECT * FROM COCHES2
MINUS
SELECT * FROM COCHES1;