/* Permite generar un único resultado */
--AVG(NUMERO)
SELECT AVG(SALARY) FROM EMPLOYEES;
--MAX(VALOR)
SELECT MAX(SALARY) FROM EMPLOYEES;
--MIN(VALOR)
SELECT MIN(SALARY) FROM EMPLOYEES;

SELECT AVG(SALARY),MAX(SALARY),MIN(SALARY) FROM EMPLOYEES;

SELECT AVG(SALARY),MAX(SALARY),MIN(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT_ID=50;

--Esto no se puede
SELECT FIRST_NAME, AVG(SALARY),MAX(SALARY),MIN(SALARY) FROM EMPLOYEES;
