SELECT * FROM EMPLOYEES;
SELECT COUNT (*) FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;
SELECT COUNT(*) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE,'yyyy')='2007';
SELECT MAX(SALARY), MIN(SALARY), MAX(SALARY) - MIN(SALARY) AS "DIFERENCIA" FROM EMPLOYEES;
SELECT SUM(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=100;
SELECT DEPARTMENT_ID,ROUND(AVG(SALARY),2) FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;
SELECT * FROM COUNTRIES;
SELECT COUNTRY_ID, COUNT(*) FROM LOCATIONS GROUP BY COUNTRY_ID;
SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL GROUP BY DEPARTMENT_ID;
SELECT TO_CHAR(HIRE_DATE,'YYYY'),COUNT(*) FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'YYYY')HAVING COUNT(*)>10;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID,MANAGER_ID HAVING COUNT(EMPLOYEE_ID) > 5;

--Esto es para que entienda que se supone que estaba haciendo el ejercicio anterior
SELECT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID, MANAGER_ID, EMPLOYEE_ID FROM EMPLOYEES;