--NVL(EXPRESSION,VALOR)--DEVUELVE UN VALOR CONCRETO
SELECT NVL('HOLA','ADIOS') FROM DUAL;
SELECT NVL(NULL,'ADIOS') FROM DUAL;
SELECT FIRST_NAME, COMMISSION_PCT FROM EMPLOYEES;
SELECT FIRST_NAME, NVL(COMMISSION_PCT,'0') FROM EMPLOYEES;
---DEVUELVE 0
SELECT FIRST_NAME,COMMISSION_PCT*SALARY, NVL(COMMISSION_PCT,0)*SALARY FROM EMPLOYEES;