SELECT NVL(NULL,'ADIOS') FROM DUAL;
SELECT FIRST_NAME, COMMISSION_PCT*SALARY, NVL(COMMISSION_PCT,0)*SALARY FROM EMPLOYEES;

--NVL2 (EXPRESSION,VALOR,VALOR2) SI NO ES NULA DEVUELVE VALOR 1 SI ES VALOR 2

SELECT FIRST_NAME,NVL2(COMMISSION_PCT, SALARY*COMMISSION_PCT,SALARY*0.1) FROM EMPLOYEES;
