--COALESCE(V1,V2,Vn) //cuando encuentra el primer valor nulo lo visualiza
SELECT COALESCE('VALOR1','VALOR2','VALOR3') from dual;
SELECT COALESCE(NULL,'VALOR2','VALOR3') from dual;
SELECT COALESCE(NULL,NULL,'VALOR3') from dual;
SELECT FIRST_NAME, TO_CHAR(COMMISSION_PCT),TO_CHAR(MANAGER_ID) FROM EMPLOYEES;
--BUSCA QUIEN NO TIENE COMMISSION NI JEFE
SELECT FIRST_NAME, COALESCE(TO_CHAR(COMMISSION_PCT),TO_CHAR(MANAGER_ID)
,'SIN JEFE NI COMISSIÓN') FROM EMPLOYEES;