--MONTHS_BETWEEN UN NUMERO DE MESES ENTRE DOS FECHAS
SELECT HIRE_DATE, MONTHS_BETWEEN(SYSDATE,HIRE_DATE) FROM EMPLOYEES;
--ADD MONTHS (F1,N)
SELECT SYSDATE,ADD_MONTHS (SYSDATE,3),SYSDATE+90 FROM DUAL;
--NEXT_DAY(FECHA,CADENA)
SELECT NEXT_DAY(SYSDATE,'MAR') FROM DUAL;