SELECT HIRE_DATE, TRUNC(SYSDATE - HIRE_DATE) FROM EMPLOYEES;
SELECT SYSDATE + 15 FROM DUAL;
SELECT SYSDATE, ROUND(MONTHS_BETWEEN('25-11-2021',SYSDATE),1) AS MESES FROM DUAL;
SELECT FIRST_NAME, HIRE_DATE,LAST_DAY(HIRE_DATE) FROM EMPLOYEES;
SELECT FIRST_NAME,HIRE_DATE, ROUND(hire_date,'MONTH') AS REDONDEO FROM EMPLOYEES WHERE ROUND(HIRE_DATE,'MONTH')>HIRE_DATE;