SELECT EMAIL,LOWER(EMAIL) FROM EMPLOYEES;
SELECT FIRST_NAME, UPPER(FIRST_NAME) FROM EMPLOYEES;
SELECT FIRST_NAME, INITCAP(FIRST_NAME) FROM EMPLOYEES;
SELECT INITCAP('ESTO ES UNA PRUEBA')AS PRUEBA FROM DUAL;