SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES;
SELECT SYSDATE FROM DUAL; --FECHA ACTUAL
--EMPIEZA A CONTAR DESDE EL 1 ENERO DE -4712 AC

--SUMAR NUMERO
SELECT SYSDATE + 2 FROM DUAL;
--RESTAR UN NUMERO
SELECT SYSDATE - 2 FROM DUAL;
--RESTAR FECHAS
SELECT HIRE_DATE,(SYSDATE - HIRE_DATE)/7 FROM EMPLOYEES; --EN SEMANAS
-- DE LA OPERACIÓN HAY QUE CALCULARLA EN HORAS, DIAS, MINUTOS