--LENGTH
SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM EMPLOYEES;
SELECT FIRST_NAME FROM EMPLOYEES WHERE LENGTH(FIRST_NAME)=6;
--SUBSTR(CADENA,POSICION,LONGITUD)
SELECT FIRST_NAME, SUBSTR(FIRST_NAME,1,3) FROM EMPLOYEES;
SELECT FIRST_NAME, SUBSTR(FIRST_NAME,3) FROM EMPLOYEES; --SI SE OMITE LA LONGITUD, TOMA A PARTIR DE LA POSICION HASTA FINALIZAR
SELECT FIRST_NAME, SUBSTR(FIRST_NAME,LENGTH(FIRST_NAME),1) FROM EMPLOYEES;--CON ESTA FUNCION ANIDADA EL LENGTH CALCULA LA LONGITUD Y EL VALOR 1 SE REFIERE A TOMAR EL ULTIMO CARACTER
--INSTR

SELECT FIRST_NAME,INSTR(FIRST_NAME,'a')FROM EMPLOYEES;--LE PREGUNTAS SI EN EL NOMBRE TIENE UNA A Y TE DEVUELVE EL VALOR NUMERICO
SELECT FIRST_NAME,INSTR(FIRST_NAME,'a')FROM EMPLOYEES WHERE INSTR (FIRST_NAME,'a')<>0; --devuelve los empleados con a distintos a cero

SELECT FIRST_NAME,INSTR(lower(FIRST_NAME),'a',4)FROM EMPLOYEES WHERE INSTR (lower(FIRST_NAME),'a',4)<>0; --busca minisculas y mayusculas a partir de la posicion 4

--LPAD Y RPAD RELLENAR EN LEFT O RIGHT
SELECT FIRST_NAME FROM EMPLOYEES;
SELECT RPAD(FIRST_NAME,20,'**') FROM EMPLOYEES;--RELLENA HASTA LLEGAR A LA LONGITUD, DESDE QUE TERMINA LA CADENA HASTA LA POSICION
SELECT LPAD(FIRST_NAME,20,'**') FROM EMPLOYEES;

--REPLACE (CADENA,ORIGINAL,NUEVA)
SELECT REPLACE(FIRST_NAME,'a','*')FROM EMPLOYEES;
--LTRIM & RTRIM ELIMINA CIERTOS CARACTERES
SELECT RTRIM('HOLA        ')||'ADIOS' FROM DUAL;
SELECT 'HOLA'||LTRIM('                                 ADIOS') FROM DUAL;
SELECT first_name,RTRIM(FIRST_NAME,'n') FROM EMPLOYEES