SELECT FIRST_NAME, LAST_NAME, SALARY AS "Salario" FROM EMPLOYEES; --esto es un comentario
SELECT DISTINCT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;-- VISUALIZAR DEPARTAMENTOS Y TIPOS DE TRABAJO
/*Este otro tipo
de comentario*/
--Practicas
SELECT FIRST_NAME, PHONE_NUMBER FROM EMPLOYEES;
SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES;
SELECT*FROM REGIONS;
SELECT COUNTRY_NAME FROM COUNTRIES;
SELECT STREET_ADDRESS As "Dirección", CITY as "Ciudad" ,STATE_PROVINCE as "Estado" FROM LOCATIONS;