SELECT 'NOMBRE: ' || FIRST_NAME || ' ' || LAST_NAME AS "NOMBRE EMPLEADO" FROM EMPLOYEES;
--NULL ES UN VALOR NULO
SELECT FIRST_NAME, SALARY, COMMISSION_PCT, SALARY * COMMISSION_PCT AS "SALARIO TOTAL" FROM EMPLOYEES; --al correr está linea genera null en commission, necesita el valor

