SELECT FIRST_NAME, LAST_NAME, SALARY AS "Salario Empleado" FROM EMPLOYEES;
SELECT FIRST_NAME, SALARY, SALARY*12 AS "Salario Anual", 20*10 AS "EJEMPLO" FROM EMPLOYEES;
SELECT 'NOMBRE: ', FIRST_NAME FROM EMPLOYEES;
SELECT 'NOMBRE: ' || FIRST_NAME || ' ' ||LAST_NAME AS "NOMBRE EMPLEADO" FROM EMPLOYEES;
SELECT FIRST_NAME, SALARY, COMMISSION_PCT, SALARY*COMMISSION_PCT AS "SALARIO TOTAL" FROM EMPLOYEES;
SELECT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES;
SELECT DEPARTMENT_ID FROM EMPLOYEES;--PUEDO YO SABER LOS DEPARTAMENTOS QUE HAY EN LA EMPRESA SIN QUE ME LOS REPITA
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES; -- VISUALIZA LOS DISTINTOS DEPARTAMENTOS SIN REPETIR
SELECT DISTINCT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES; --RECUPERA LAS FILAS Y ELIMINA LOS DUPLICADOS 