--DECODE (vALOR,C1,V1,C2,V2,V3)
/*CONDICIONAL, SI EL VALOR CUMPLE CON
EL CONDICIONAL 1 TOMARÁ EL VALOR V1, SINO
SEGUIRÁ TESTEANDO, EN CASO CONTRARIO DEVOLVERÁ
UN ELSE */

SELECT FIRST_NAME, DEPARTMENT_ID, 
DECODE(DEPARTMENT_ID,50,'INFORMATICA',10,'VENTAS','OTRO TRABAJO')
FROM EMPLOYEES;


