--TO_CHAR()
--TO DATE
-- TO NUMBER

SELECT '10' +10 FROM DUAL; --DETECTA LA CADENA A NUMEROS
SELECT MONTHS_BETWEEN(SYSDATE,'10-10-18') FROM DUAL; --LO IDEAL ES TENER EL CONTROL Y CONVERTIR O REALIZAR LA FUNCION
SELECT 10||'10' FROM DUAL; --CONCATENA CARACTERES Y NUMEROS
SELECT 'HOY ES: ' || SYSDATE FROM DUAL; --CARACTER MÁS FECHA, ORACLE NO SERÁ CAPAZ DE HACER FUNCIONES IMPLICITAS


--TO_CHAR(DATE/NUMBER,'FORMATO')
/*
YYYY    AÑO 4 NUMEROS
YEAR    AÑO(INGLÉS)
MM      MES 2 DIGITOS
MONTH   MES EN TEXTO
MON     ABREVIATURA DEL MES
DY      ABREVIATURA DEL DIA
DAY     DIA EN TEXTO
DD      NUMERO DEL DIA
*/

SELECT SYSDATE, TO_CHAR(SYSDATE,'YYYY')FROM DUAL; --TOMA LA CADENA Y LA DEVUELVE EN FORMATO 4 NUMEROS AÑOS
SELECT SYSDATE, TO_CHAR(SYSDATE,'MM') FROM DUAL;
SELECT SYSDATE, TO_CHAR(SYSDATE,'YEAR') FROM DUAL; --- EN INGLES
SELECT SYSDATE, TO_CHAR(SYSDATE,'DAY') FROM DUAL; --- EN ESPAÑOL

/*TO_CHAR(DATE,'FORMATO')
AM      PM MERIDIAN
HH      FORMATO EN 12 HORAS
HH24    FORMATO 24 HORAS
MI      MINUTO
SS      SEGUNDO
*/
SELECT SYSDATE, TO_CHAR(SYSDATE,'HH') FROM DUAL; --OBTIENE LA HORA EN FORMATO 12 HORAS
SELECT SYSDATE, TO_CHAR(SYSDATE,'HH24') FROM DUAL; --OBTIENE LA HORA EN FORMATO 24 HORAS
SELECT SYSDATE, TO_CHAR(SYSDATE,'MI') FROM DUAL; -- OBTIENE LOS MINUTOS

SELECT SYSDATE, TO_CHAR(SYSDATE,'"SON LAS" HH24:MI "DEL DIA DEL HOY DEL AÑO" YYYY') AS FECHA FROM DUAL; -- C0MBINAR CARACTERES CON EL FORMATO DE 24 HORAS Y MINUTOS, ES CONVENIENTE AGREGAR COMILLAS