-- TO_CHAR(NUMERO,'FORMATO')
/*
9 NUMERO
0 VISUALIZA UN CERO
$ DOLAR
L MONEDA ACTUAL
. PUNTO DECIMAL
, MILES SEPARADOR   
*/


SELECT SALARY,TO_CHAR(SALARY,'99999'),TO_CHAR(SALARY,'00009'),--LO CONVIERTE EN FORMATO CARACTERES, EN LA SEGUNDA PARTE INDICA QUE SI NO POSEE UN NUMERO  LO CONVIERTE EN CERO
TO_CHAR(SALARY,'$00009'),TO_CHAR(SALARY,'L00009.99')
FROM EMPLOYEES; 