SELECT * FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE,'MM')=5 ;
SELECT * FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE,'YYYY')=2007;
SELECT TO_CHAR(TO_DATE('25-11-1995'),'DAY') AS DIA_DE_NACIMIENTO FROM DUAL;
SELECT FIRST_NAME,HIRE_DATE FROM EMPLOYEES WHERE RTRIM(TO_CHAR(HIRE_DATE,'MONTH'))='JUNIO';
SELECT FIRST_NAME, TO_CHAR(SALARY*20,'L9,999,999.99')AS MONEDA_ACTUAL, TO_CHAR(SALARY,'$999,999.99')AS DOLARES, SALARY FROM EMPLOYEES;
