SELECT * FROM TAB; --MUESTRA LAS TABLAS
CREATE TABLE STUDENTS --Da click en create table y DDL
(
STUDENT_ID NUMBER(4) NOT NULL
, FIRST_NAME VARCHAR2(20)
, LAST_NAME VARCHAR2(20) NOT NULL
, CLASS VARCHAR2(10) NOT NULL
);
