--SQL:1999 ANSI
SELECT EMP.SALARY FROM EMPLOYEES EMP;
--NATURAL JOIN
--Unir tabla Regions and Countries
SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM REGIONS NATURAL JOIN COUNTRIES;
SELECT REGION_ID, REGION_NAME,COUNTRY_ID,
COUNTRY_NAME FROM 
REGIONS RE NATURAL JOIN COUNTRIES CO;