SELECT D.DEPARTMENT_NAME, E.FIRST_NAME --unir las tablas con las siglas
FROM EMPLOYEES E JOIN DEPARTMENTS D
 USING (department_id);
 
 SELECT DEPARTMENT_NAME, FIRST_NAME FROM EMPLOYEES NATURAL JOIN 
 --LA E ES ALIAS
 DEPARTMENTS; --MANAGER_ID DE EMPLEADOS ES EL JEFE Y MANAGER_ID 
 --DEPARTMENTS SON DISTINTOS, NO SE PUEDE USAR EL NATURAL JOIN