SELECT DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME
FROM EMPLOYEES E JOIN departments d
    USING (department_id)
WHERE SALARY > 5000;

SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME
FROM EMPLOYEES E JOIN departments d
  ON (E.department_id=D.DEPARTMENT_ID)
  JOIN LOCATIONS L
  ON (D.LOCATION_ID=L.LOCATION_ID)
  AND SALARY > 5000;
 WHERE SALARY >500;