--JOIN USANDO WHERE
SELECT DEPARTMENT_NAME,FIRST_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID;
--No es lo más recomendable, pero no está demás verlo
SELECT DEPARTMENT_NAME,FIRST_NAME,CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L 
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND L.LOCATION_ID=D.LOCATION_ID;
