--OUTER JOINS
SELECT DEPARTMENT_NAME, FIRST_NAME
FROM DEPARTMENTS D JOIN EMPLOYEES E
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;
-- SI VERIFICAS EL EMPLOYEE HAY 107 NO 106
--KIMBERLY GRANT NO TIENE DEPARTAMENTO
--NOMBRE DEL DEPARTAMENTO Y EMPLEADO!!!!

--OUTER JOINS HAY 3 TIPOS
--LEFT OUTER
--RIGHT OUTER
--FULL OUTER

--INNER JOIN (TODOS LOS QUE HEMOS HECHO SON)