/*UNA TRANSACCION ES UN CONJUNTO DE OPERACIONES
CONTRA LA BASE DE DATOS: 

!!!!!DEBEN SER REALIZADAS O RECHAZADAS TODAS!!!!!

NO PUEDEN SER REALIZADA PARCIALMENTE

CUANDO SE INSERTA UN EMPLEADO POR EJEMPLO, SE MODIFICA
EL DEPARTAMENTO,SE BORRAN DATOS QUE YA NO VALEN, TODAS ESTAS
OPERACIONES SE LLEVAN EN CONJUNTO

CUANDO SE TERMINA LA TRANSACCION SE HACE O UN COMMIT O UN ROLLBACK
O SE ACEPTA O SE RECHAZA*/

--COMMIT O ROLLBACK
INSERT INTO REGIONS1 VALUES(100,'AUSTRALIA'); --AQUI YA EMPEZAMOS UNA TRANSACCION
--COMMIT
--ROLLBACK

-- REQUIREN COMMIT O ROLLBACK
--DDL CREATE TABLE
--DCL GRANT

--ORACLE HACE UN ROLLBACK CUANDO SE PRODUCE UN ERROR O FALLO EN LA MÁQUINA
--FALLO ROLLBACK

--HAY COMMIT AUTOMÁTICOS POR EJEMPLO SQL+

/*CONECTARSE USANDO CMD SQLPLUS HR/hr*/