--CONECTARSE A SQLPLUS MEDIANTE CMD SQLPLUS username/password
SELECT * FROM REGIONS1;
--ESTÁ TRUNCADO
INSERT INTO REGIONS1 VALUES(100,'AUSTRALIA');
--CORROBORAR EN SQLPLUS
--NO DEBE DE APARACER NINGUNA FILA
--SE TIENE QUE HACER EL COMMIT PARA QUE OTROS USUARIOS PUEDAN VERLO
INSERT INTO REGIONS1 VALUES(200,'EUROPA');
--CORROBORAR NUEVAMENTE EN SQLPLUS
--NUEVAMENTE NO DEBE DE APARECER NADA
COMMIT;
--CORROBORAR EN SQLPLUS
--DEBEN DE APARACER LOS DATOS
--HACER ROLLBACK
INSERT INTO REGIONS1 VALUES(300,'AMERICA');
INSERT INTO REGIONS1 VALUES(400,'ASIA');
--DESHACE LOS CAMBIOS
ROLLBACK;
--SE PUEDE TENER VARIOS SQLDEVELOPER ABIERTOS