-- TRABAJAR CON DOS USUARIOS

--UN BLOQUEO ES UN TESTIGO QUE TOMAS Y QUE NADIE PUEDE MODIFICAR
--HASTA QUE TERMINES
SELECT * FROM REGIONS1;
UPDATE REGIONS1 SET REGION_NAME='XXXX' 
WHERE REGION_ID=100;
--SI SE EJECUTA ESTA MISMA OPERACIÓN EN EL OTRO USUARIO SE QUEDA CONGELADA
/*Esto se debe a que está esperando a que terminé esta operación, se queda
bloqueado, se desbloquea con un commit o un rollback*/
COMMIT;