INSERT INTO PRODUCTOS2(CODE,NAME) VALUES(1,'CLAVOS');
SELECT * FROM PRODUCTOS2;
COMMIT;
DELETE PRODUCTOS2;
SELECT * FROM PRODUCTOS2;
ROLLBACK;
SELECT * FROM PRODUCTOS2;
--TRABAJAR CON UN SAVEPOINT
INSERT INTO PRODUCTOS2(CODE,NAME) VALUES(2,'ARANDELAS');
INSERT INTO PRODUCTOS2(CODE,NAME) VALUES(3,'ESCARPIAS');
SAVEPOINT A;
SELECT * FROM PRODUCTOS2;
UPDATE PRODUCTOS2 SET NAME='TORNILLOS'
WHERE CODE=3;
ROLLBACK TO SAVEPOINT A;
SELECT * FROM PRODUCTOS2;
COMMIT;