--INLINE VIEWS VISTAS DINAMICAS PARA OPERACIONES COMPLEJAS
CREATE VIEW VISTA_EMPLE AS SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT * FROM VISTA_EMPLE WHERE SALARY > 5000;

--VISTAS INLINA SE CREA, SIN TENER QUE HACER EL CREATE VIEW
SELECT FIRST_NAME,SALARY FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC) WHERE SALARY > 5000;
--CREAR EN TABLA ESTATICA
CREATE TABLE REGIONES1 AS SELECT * FROM REGIONS;
SELECT * FROM REGIONES1;
CREATE VIEW VIEW_REGIONES AS SELECT * FROM REGIONES1;
INSERT INTO VIEW_REGIONES VALUES(5,'Antartica');
--CREAR LISTA DINAMICA
INSERT INTO (SELECT * FROM REGIONES1) VALUES(6,'Australia');

UPDATE (SELECT * FROM REGIONES1 WHERE REGION_ID> 3) SET REGION_NAME=LOWER(REGION_NAME);
