SELECT *
FROM (SELECT CLIENTE,PRODUCTO, CANTIDAD FROM   pivot)
PIVOT  
(SUM(CANTIDAD) FOR (PRODUCTO) IN 
('AGUACATES' AS "AGUACATES",'BANANAS' AS "BANANA",'MANZANA' AS "MANZANA",'NARANJA' AS "NARANJA"));

CREATE TABLE UN_PIVOT AS
SELECT *
FROM   (SELECT CLIENTE,PRODUCTO, CANTIDAD FROM   pivot)
PIVOT  (SUM(CANTIDAD) FOR (PRODUCTO) IN ('AGUACATES' AS "AGUACATES",'BANANAS' AS "BANANA",'MANZANA' AS "MANZANA",'NARANJA' AS "NARANJA"));

SELECT * FROM UN_PIVOT;

--PARA CONVERTIR DE CROSSTABLE A TABLA NORMAL SE USA:
SELECT * FROM UN_PIVOT 
UNPIVOT (CANTIDAD FOR PRODUCTO IN ("AGUACATES","BANANA","MANZANA","NARANJA"))--NOMBRES DE LAS COLUMNAS
ORDER BY CLIENTE,PRODUCTO;