CREATE TABLE EMPLES_JEFES (COD_EMPLE NUMBER, NOMBRE VARCHAR2(100), SALARIO NUMBER);
CREATE TABLE EMPLES_MANDOS (COD_EMPLE NUMBER, NOMBRE VARCHAR2(100), SALARIO NUMBER,DEPARTAMENTO NUMBER);
CREATE TABLE EMPLES_NORMALES (COD_EMPLE NUMBER, NOMBRE VARCHAR2(100), SALARIO NUMBER, RESPONSABLE NUMBER);

--INSERT ALL CON CONDICIONES
INSERT ALL
    WHEN SALARY > 10000 THEN
    INTO EMPLES_JEFES VALUES(EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME,SALARY)
    WHEN SALARY BETWEEN 8000 AND 10000 THEN
    INTO EMPLES_MANDOS VALUES(EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME, SALARY,DEPARTMENT_ID)
    WHEN SALARY < 8000 THEN
    INTO EMPLES_NORMALES VALUES(EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME,SALARY,MANAGER_ID)
    --AGREGAR WHEN PARA DATOS FINANCIEROS
    WHEN DEPARTMENT_ID=100 THEN
    INTO FINANCIERO VALUES(EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME,SALARY,MANAGER_ID)
   ---SE PUEDE USAR UN: ELSE
SELECT * FROM EMPLOYEES;

SELECT COUNT(*) FROM EMPLES_JEFES;
SELECT COUNT(*) FROM EMPLES_MANDOS;
SELECT COUNT(*) FROM EMPLES_NORMALES;

--GUARDAR LOS DATOS FINANCIEROS EN OTRA TABLA
CREATE TABLE FINANCIERO(COD_EMPLE NUMBER, NOMBRE VARCHAR2(100), SALARIO NUMBER, RESPONSABLE NUMBER);
SELECT COUNT(*) FROM FINANCIERO;
