--ROLLUP
--CUBE
SELECT DEPARTMENT_ID,SUM(SALARY) AS "SALARIO"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;


SELECT DEPARTMENT_ID,SUM(SALARY) AS "SALARIO"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY ROLLUP(DEPARTMENT_ID) --HARÁ EL GROUP BY NORMAL Y SACARÁ EL TOTAL EN LA ÚLTIMA FILA
ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID,JOB_ID,SUM(SALARY) AS "SALARIO"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY ROLLUP(DEPARTMENT_ID,JOB_ID) --HARÁ TODO EL PAQUETE
ORDER BY DEPARTMENT_ID,JOB_ID;