--CUBE PARA ENTORNOS TRIDIMENSIONALES,
SELECT DEPARTMENT_ID,JOB_ID,SUM(SALARY) AS "SALARIO"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY ROLLUP(DEPARTMENT_ID,JOB_ID)
ORDER BY DEPARTMENT_ID,JOB_ID;
--MEZCLA DATOS

--UN ZOOM POR 1) DEPARTMENT_ID Y JOB_ID
--2) DEPARTMENT_ID, 3)JOB_ID, 4)TOTAL HACE 4 GRANDES TOTALES 
SELECT DEPARTMENT_ID,JOB_ID,SUM(SALARY) AS "SALARIO"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY CUBE(DEPARTMENT_ID,JOB_ID)
ORDER BY DEPARTMENT_ID,JOB_ID;

--EJEMPLO 3 DIMENSIONES
SELECT CITY, DEPARTMENT_NAME, COUNT(*) AS EMPLEADOS
FROM LOCATIONS NATURAL JOIN DEPARTMENTS JOIN EMPLOYEES USING (DEPARTMENT_ID)
GROUP BY CITY,DEPARTMENT_NAME
ORDER BY CITY, DEPARTMENT_NAME;

SELECT CITY, DEPARTMENT_NAME, COUNT(*) AS EMPLEADOS
FROM LOCATIONS NATURAL JOIN DEPARTMENTS JOIN EMPLOYEES USING (DEPARTMENT_ID)
GROUP BY ROLLUP(CITY,DEPARTMENT_NAME)
ORDER BY CITY, DEPARTMENT_NAME;

--HACE TOTAL POR CIUDAD, TOTAL POR DEPARTAMENTO Y TOTAL DE TOTALES
SELECT CITY, DEPARTMENT_NAME, COUNT(*) AS EMPLEADOS
FROM LOCATIONS NATURAL JOIN DEPARTMENTS JOIN EMPLOYEES USING (DEPARTMENT_ID)
GROUP BY CUBE(CITY,DEPARTMENT_NAME)
ORDER BY CITY, DEPARTMENT_NAME;

--1) CIUDAD,DEPARTAMENTO, TIPO, 2) SOLO POR CIUDAD, DEPARTAMENTO 3)POR CADA JOB ID
--4)POR CIUDAD
SELECT CITY, DEPARTMENT_NAME, JOB_ID,COUNT(*) AS EMPLEADOS
FROM LOCATIONS NATURAL JOIN DEPARTMENTS JOIN EMPLOYEES USING (DEPARTMENT_ID)
GROUP BY CUBE(CITY,DEPARTMENT_NAME,JOB_ID)
ORDER BY CITY, DEPARTMENT_NAME,JOB_ID;